# Generated by Django 3.1 on 2020-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.AddField(
            model_name='history',
            name='productname',
            field=models.CharField(default='Product', max_length=50),
        ),
    ]
