# Generated by Django 3.1 on 2020-08-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200824_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='productname',
            new_name='product',
        ),
    ]
