# Generated by Django 3.1 on 2020-08-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_notificationcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='productuser',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.CharField(default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='sold_to',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
