# Generated by Django 3.1 on 2020-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_auto_20200922_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
