# Generated by Django 3.1 on 2020-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_auto_20200923_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='product_name',
            field=models.CharField(default='product_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.CharField(default='product_id', max_length=20),
        ),
    ]
