# Generated by Django 3.1 on 2020-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_auto_20200923_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.CharField(default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='product_name',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
