# Generated by Django 3.1 on 2020-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_auto_20200923_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product_name',
            field=models.IntegerField(default=0),
        ),
    ]
