# Generated by Django 3.1 on 2020-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_auto_20200923_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product_name',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
