# Generated by Django 3.1 on 2020-09-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_auto_20200923_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='product_name',
            new_name='productname',
        ),
    ]
