# Generated by Django 3.1 on 2020-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_auto_20200923_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='productcategory',
            field=models.CharField(default='product', max_length=50),
        ),
        migrations.AddField(
            model_name='history',
            name='productimg',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='history',
            name='productprice',
            field=models.IntegerField(default=0),
        ),
    ]
