# Generated by Django 3.1 on 2020-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0020_auto_20200923_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_to', models.CharField(default='user', max_length=20)),
                ('product', models.CharField(default='product', max_length=20)),
                ('productname', models.CharField(default='product', max_length=50)),
                ('productcategory', models.CharField(default='product', max_length=50)),
                ('productprice', models.IntegerField(default=0)),
                ('productimg', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('productuser', models.CharField(default='user', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
