# Generated by Django 3.1 on 2020-09-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_sold_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_out',
            name='sold_to',
        ),
    ]
