# Generated by Django 3.1 on 2020-09-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_lookingfor'),
        ('Account', '0023_sold_out_sold_to'),
    ]

    operations = [
    ]
